### ISSUE TITLE
Empty alignment files

### ISSUE THREAD

**Issue by JudithNeukamm** [Integrative-Transcriptomics/MUSIAL#1]
After running MUSIAL, the alignment files ('snvAlignment_excluded.fasta' and 'snvAlignment.fasta') are missing the sequences, the headers are present. File 'genomeAlignment.fasta' contains only 'N' as the sequence. 
The error seems to happen in class 'SNVTable.java' in the method 'toAlignment, line 612'. The variable snpPos is empty (contains no sequence information).

**Comment by zxmmx04** [comment]
Hey,
these lines are required to be able to reconstruct multi-reference samples, when e.g. the reads were mapped against a bacterial genome including the plasmids. This would then reconstruct all the sequences in the reference.
Otherwise the mapping between the different sequences is not possible and it may happen that the SNVs from the different sequences are mixed together, which would be bad.

The results are empty if the fasta header does not match the sequence column in the vcf file perfectly

Best,
Alex

**Comment by JudithNeukamm** [comment]
Thank you for the answer. 
However, I used exactly the same reference for creating the VCF file and running MUSIAL, and I get 'this.contigName=NC_003143.1' and 'this.sequenceHeader=NC_003143.1 Yersinia pestis CO92 chromosome, complete genome'. I suppose that the contigName is cut after the space, where the sequenceHeader isn't. 
Shouldn't this be catched in the code? Or do I have to take care as a user (manually)?

**Comment by zxmmx04** [comment]
I added an additional statement to also look for the trunkated string
